-- Add GUID column to messages table
-- Version: 0.2.0
-- Created: 2025-11-11

-- Add guid column (UUID format) - SQLite doesn't support UNIQUE in ALTER TABLE
-- We'll add it as nullable first, then populate and add unique constraint via application
ALTER TABLE messages ADD COLUMN guid TEXT;

-- Create index on guid for fast lookups
CREATE INDEX IF NOT EXISTS idx_messages_guid ON messages(guid);

-- Note: GUIDs will be generated by the application when messages are created
-- For existing messages, run the update script to populate GUIDs

