#!/usr/bin/env python3
# Copyright 2026 Cloud-Dog, Viewdeck Engineering Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
AT1.17: Comprehensive Email Validation Test

Validates (API-visible):
- Email delivery reaches sent/delivered and is accepted (no last_error)
- personalised_payload contains subject/body/content type
- message link and attachment presence when generated by system

All values are config-driven via --env private/env-test-at117.
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Dict, List, Tuple

import pytest


def _require_str(test_config: Any, key: str) -> str:
    v = test_config.get(key)
    if v is None or v == "":
        pytest.fail(f"❌ HARD FAIL: {key} not configured in env file")
    return str(v)


def _read_example_file(repo_root: Path, filename: str) -> str:
    p = repo_root / "tests" / "Examples" / filename
    if not p.exists():
        pytest.fail(f"❌ HARD FAIL: example file not found: {p}")
    return p.read_text(encoding="utf-8")


def _pick_enabled_smtp_channel_name(api_client) -> str:
    r = api_client.get("/channels")
    assert r.status_code == 200, f"GET /channels failed: {r.status_code} {r.text[:200]}"
    channels = r.json()
    assert isinstance(channels, list), "Expected /channels to return a list"
    for ch in channels:
        if not isinstance(ch, dict):
            continue
        if str(ch.get("type", "")).lower() == "smtp" and bool(ch.get("enabled")) is True:
            name = ch.get("name")
            if name:
                return str(name)
    pytest.fail("No enabled SMTP channel found via API /channels (required for AT1.17)")


def _wait_for_delivery_sent(
    api_client,
    message_id: int,
    *,
    max_wait: float,
    poll_interval: float,
) -> Dict[str, Any]:
    t0 = time.time()
    last_state: str | None = None
    while time.time() - t0 < max_wait:
        r = api_client.get(f"/messages/{message_id}/deliveries")
        assert r.status_code == 200, f"GET /messages/{{id}}/deliveries failed: {r.status_code} {r.text[:200]}"
        data = r.json()
        items = data.get("items") if isinstance(data, dict) else None
        deliveries = items if isinstance(items, list) else (data if isinstance(data, list) else [])
        if deliveries and isinstance(deliveries[0], dict):
            d = deliveries[0]
            last_state = str(d.get("state") or d.get("status") or "").lower()
            elapsed = time.time() - t0
            print(f"[{elapsed:6.1f}s] message {message_id}: delivery_state={last_state}")
            if last_state in ("sent", "delivered"):
                return d
            if last_state in ("hard_failed", "soft_failed", "failed", "cancelled", "canceled"):
                pytest.fail(f"❌ Delivery reached terminal failure state: {last_state} ({d.get('last_error')})")
        time.sleep(poll_interval)
    pytest.fail(f"❌ Timed out waiting for delivery (last_state={last_state!r}, waited {max_wait}s)")


def _parse_personalised_payload(delivery: Dict[str, Any]) -> Tuple[str, str, str, List[Dict[str, Any]]]:
    pp = delivery.get("personalised_payload")
    assert pp is not None, "❌ personalised_payload missing on delivery"
    pp_obj = json.loads(pp) if isinstance(pp, str) else pp
    if isinstance(pp_obj, dict):
        attachments = pp_obj.get("attachments") if isinstance(pp_obj.get("attachments"), list) else []
        return (
            str(pp_obj.get("subject") or ""),
            str(pp_obj.get("body") or ""),
            str(pp_obj.get("content_type") or ""),
            [a for a in attachments if isinstance(a, dict)],
        )
    if isinstance(pp_obj, list) and pp_obj and isinstance(pp_obj[0], dict):
        # Content blocks - no subject
        return ("", str(pp_obj[0].get("body") or ""), str(pp_obj[0].get("type") or ""), [])
    pytest.fail("❌ Unexpected personalised_payload shape")
@pytest.mark.AT
@pytest.mark.mcp
@pytest.mark.req("FR-023")


def test_at1_17a_email_payload_links_and_attachments_visible_via_api(
    api_client,
    test_config,
    request,
    at117_max_wait: float,
    at117_poll_interval: float,
    smtp_channel_name: str,
):
    run_id = str(int(time.time()))

    repo_root = Path(__file__).resolve().parents[3]
    example_file = _require_str(test_config, "test.at117.example_file")
    subject_expected = _require_str(test_config, "test.at117.subject")
    recipient_email = _require_str(test_config, "test.at117.recipient_email")
    pref_language = _require_str(test_config, "test.at117.pref_language")
    pref_content_style = _require_str(test_config, "test.at117.pref_content_style")
    message_base_url = _require_str(test_config, "messages.base_url")

    # Make content large enough to exercise link/attachment behaviour.
    content = _read_example_file(repo_root, example_file)
    max_chars = int(float(_require_str(test_config, "test.at117.max_chars")))
    content = content[:max_chars]

    created_message_id: int | None = None

    def _cleanup() -> None:
        if created_message_id is not None:
            try:
                api_client.delete(f"/messages/{created_message_id}")
            except Exception:
                pass

    request.addfinalizer(_cleanup)

    msg = api_client.post(
        "/messages",
        json={
            "audience_type": "personalised",
            "destinations": [
                {
                    "channel": smtp_channel_name,
                    "address": recipient_email,
                    "preferences": {"language": pref_language, "content_style": pref_content_style},
                }
            ],
            "content": [{"type": "text", "body": content}],
            "options": {"subject": f"{subject_expected} ({run_id})"},
        },
    )
    assert msg.status_code == 201, f"POST /messages failed: {msg.status_code} {msg.text[:200]}"
    created_message_id = int(msg.json().get("message_id"))
    assert created_message_id > 0

    delivery = _wait_for_delivery_sent(api_client, created_message_id, max_wait=at117_max_wait, poll_interval=at117_poll_interval)
    assert delivery.get("last_error") in (None, ""), f"❌ Delivery rejected: {delivery.get('last_error')}"

    subject, body, content_type, attachments = _parse_personalised_payload(delivery)

    assert body.strip() != "", "❌ Empty email body"
    # Subject should not be empty and should include our requested subject substring when present
    if subject:
        assert subject_expected in subject, f"❌ Subject did not include expected token {subject_expected!r}: {subject!r}"

    # Link validation (API-visible)
    assert message_base_url in body, f"❌ Expected message link base {message_base_url!r} in body"

    # Attachment validation (best-effort; only assert structure if present)
    for a in attachments:
        assert str(a.get("filename") or "").strip() != "", "❌ Attachment missing filename"
        # Attachment content may be in `content` or may be referenced; accept either but must not be totally empty.
        assert any(str(a.get(k) or "").strip() for k in ("content", "uri", "url")), "❌ Attachment missing content/uri/url"

# W28A-202 marker augmentation
_w28a_202_existing_pytestmark = globals().get("pytestmark", [])
if not isinstance(_w28a_202_existing_pytestmark, list):
    _w28a_202_existing_pytestmark = [_w28a_202_existing_pytestmark]
pytestmark = _w28a_202_existing_pytestmark + [pytest.mark.application, pytest.mark.smtp, pytest.mark.heavy]
